#!/usr/bin/env bash
# Create / reset the dedicated test database, then run alembic up to head
# against it. Idempotent — safe to run repeatedly.
#
# Reads the dev DATABASE_URL from .env to figure out the host/user/password,
# then forces the db name to TEST_DB (default: myblog_test). Writes a
# .env.test file you can source before running pytest.
#
# Usage:
#   bash scripts/bootstrap-test-db.sh
#   set -a; source .env.test; set +a
#   uv run pytest -q
set -euo pipefail

cd "$(dirname "$0")/.."   # → backend/

if [[ ! -f .env ]]; then
  echo "✗ backend/.env not found — copy .env.example first." >&2
  exit 1
fi

# Pull DATABASE_URL from .env (no shell-eval; just grep+strip).
DEV_URL=$(grep -E '^DATABASE_URL=' .env | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")
if [[ -z "${DEV_URL}" ]]; then
  echo "✗ DATABASE_URL not set in .env" >&2
  exit 1
fi

TEST_DB="${MYBLOG_TEST_DB_NAME:-myblog_test}"

# Strip +asyncpg driver hint and replace the trailing /<db_name> with /<test_db>.
BARE_URL="${DEV_URL/postgresql+asyncpg:/postgresql:}"
SERVER_URL=$(echo "${BARE_URL}" | sed -E 's|/[^/]+$||')          # e.g. postgresql://user:pw@host:5432
TEST_URL="${SERVER_URL}/${TEST_DB}"
TEST_URL_ASYNC="${TEST_URL/postgresql:/postgresql+asyncpg:}"

echo "▶ test DB url       : ${TEST_URL}"
echo "▶ dropping if exists, recreating ..."

# Drop+create via asyncpg against the postgres maintenance DB (no psql dependency).
PG_MAINT_URL="${SERVER_URL}/postgres"
TEST_DB="${TEST_DB}" PG_MAINT_URL="${PG_MAINT_URL}" uv run python - <<'PY' >/dev/null
import asyncio, os
import asyncpg

async def main() -> None:
    url = os.environ["PG_MAINT_URL"]
    db = os.environ["TEST_DB"]
    conn = await asyncpg.connect(url)
    try:
        # Sever any other sessions on the target DB so DROP succeeds.
        await conn.execute(
            "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
            "WHERE datname=$1 AND pid<>pg_backend_pid()", db,
        )
        await conn.execute(f'DROP DATABASE IF EXISTS "{db}"')
        await conn.execute(f'CREATE DATABASE "{db}"')
    finally:
        await conn.close()

asyncio.run(main())
PY

echo "▶ alembic upgrade head against ${TEST_DB} ..."
DATABASE_URL="${TEST_URL_ASYNC}" uv run alembic upgrade head >/dev/null

echo "▶ seed default tags + site_meta + admin ..."
DATABASE_URL="${TEST_URL_ASYNC}" uv run python -m app.cli seed bootstrap >/dev/null
DATABASE_URL="${TEST_URL_ASYNC}" uv run python -m app.cli seed admin \
    --email hi@wangyang.dev --password changeme >/dev/null

cat > .env.test <<EOF
# Auto-generated by scripts/bootstrap-test-db.sh
# Source before running tests:  set -a; source .env.test; set +a
DATABASE_URL=${TEST_URL_ASYNC}
EOF

echo "✓ test DB ready : ${TEST_DB}"
echo "✓ wrote         : backend/.env.test"
echo
echo "Next:"
echo "  set -a; source .env.test; set +a"
echo "  uv run pytest -q"
