"""initial

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-26 00:12:42.037587

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('tfa_secret_encrypted', sa.String(length=256), nullable=True),
    sa.Column('tfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('magic_link_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_accounts_singleton'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('href', sa.String(length=512), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrib_days',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_log_created_at', 'event_log', ['created_at'], unique=False)
    op.create_index('ix_event_log_type_created', 'event_log', ['type', 'created_at'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=32), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','maintained','archived')", name='ck_projects_status'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('site_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('tagline', sa.String(length=256), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('github', sa.String(length=64), nullable=False),
    sa.Column('pronouns', sa.String(length=32), nullable=True),
    sa.Column('avatar_path', sa.String(length=256), nullable=True),
    sa.Column('typing_line', sa.Text(), nullable=False),
    sa.Column('stack_chips', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('footer_note', sa.String(length=256), nullable=False),
    sa.Column('default_theme', sa.String(length=8), nullable=False),
    sa.Column('accent_color', sa.String(length=32), nullable=False),
    sa.Column('accent2_color', sa.String(length=32), nullable=False),
    sa.Column('violet_color', sa.String(length=32), nullable=False),
    sa.Column('danger_color', sa.String(length=32), nullable=False),
    sa.Column('launched_at', sa.Date(), nullable=False),
    sa.Column('pet_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_site_meta_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_tags_slug')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('n', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('read', sa.String(length=16), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tldr', sa.Text(), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('body_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('comments_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lang in ('zh','en')", name='ck_posts_lang'),
    sa.CheckConstraint("status in ('draft','published','scheduled')", name='ck_posts_status'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_status_date', 'posts', ['status', 'date'], unique=False)
    op.create_index('ix_posts_tag_status_date', 'posts', ['tag_id', 'status', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_tag_status_date', table_name='posts')
    op.drop_index('ix_posts_status_date', table_name='posts')
    op.drop_table('posts')
    op.drop_table('tags')
    op.drop_table('site_meta')
    op.drop_table('projects')
    op.drop_index('ix_event_log_type_created', table_name='event_log')
    op.drop_index('ix_event_log_created_at', table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('contrib_days')
    op.drop_table('contacts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
